server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/demo-1214?serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    #    password: 123456
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    #    lettuce:
    #      shutdown-timeout: 0
    database: 0
    timeout: 5000
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB

#    url: jdbc:mysql://localhost:3306/demo-1214?serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
  params: count=countSql
logging:
  level:
    com.binge.controller: info
  file:
    path: d:/logs
  logback:
    rollingpolicy:
      max-file-size: 1MB

